{% set name = "netpbm" %}
{% set version = "10.73.29" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/netpbm/files/super_stable/{{ version }}/netpbm-{{ version }}.tgz
  sha256: e4871805d3be46b98047a30774186da3fef0855ee4fe31eb9c16c5e5cffa96d9

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - flex
    - gettext
    - make
    - sed
  host:
    - perl
    - jpeg
    - libtiff
    - zlib
    - libpng
    - libxml2
    - ghostscript
  run:
    - perl
    - jpeg
    - libtiff
    - zlib
    - libpng
    - libxml2
    - ghostscript

test:
  commands:
    - pnmtopng -version
    - pnmtops -version
    - ppmtogif -version
    - pamscale -version
    - tifftopnm -version
    - jpegtopnm -version
    - ppmtopgm -version
    - pamcut -version
    - bmptopnm -version

about:
  home: http://netpbm.sourceforge.net
  license: OTHER
  license_file: doc/copyright_summary
  summary: 'Netpbm is a toolkit for manipulation of graphic images, including conversion of images between a variety of different formats.'
  doc_url: http://netpbm.sourceforge.net/doc/
  dev_url: http://svn.code.sf.net/p/netpbm/code/

extra:
  recipe-maintainers:
    - juliotux
